/**
 * Cloudflare Worker for AI Podcast Generation
 * This file contains the corrected logic for concatenating multiple audio streams (ReadableStream)
 * generated by the AI service and returning the final combined audio.
 */

import { Ai } from '@cloudflare/ai';

export interface Env {
  // If you set another name in the Wrangler config file as the value for 'binding',
  // replace "AI" with the variable name you defined.
  AI: Ai;
}

export default {
    async fetch(request, env): Promise<Response> {

        const response = await env.AI.run(
            // @ts-ignore
            "@cf/meta/llama-3.1-8b-instruct-fast",
            {
                prompt: `
                Generate a simple podcast script with 2 hosts:
                - Alex (knowledgeable and calm)
                - Jamie (inquisitive, upbeat)

                Topic: 'The incredible engineering of the human brain'

                REQUIREMENTS:
                1. Generate exactly 5 lines from each host (10 lines total)
                2. Start with Alex introducing the topic
                3. Hosts can ask questions, but REPLACE ALL QUESTION MARKS WITH PERIODS
                4. Alex's first line MUST include:
                    - A greeting
                    - Introduction of both hosts by name
                    - Introduction to "The Breakdown AI Podcast"
                    - A short summary of the topic before diving into the subject
                    - This initial line must be at least 5 sentences long
                5. Jamie's final line MUST close out the podcast with a closing statement that includes their names and thanks the listener
                6. Alternate between Alex and Jamie (bouncing back and forth)

                FORMAT:
                - Each line must start with the speaker's name in brackets followed by a colon
                - Each line must be separated by TWO newlines (\n\n)
                - Example format:
                [Alex]:Wonderful Day We're having!

                [Jamie]:It sure is!

                DO NOT include any additional text, greetings, or explanations.
                OUTPUT EXACTLY 10 LINES TOTAL (5 from Alex, 5 from Jamie) in the specified format.
                `,
                max_tokens: 3000,
            }
        );

        console.log("Recived response from AI\n");

        // 1. Parse lines and split by speaker
        // @ts-ignore
        let lines: string[] = response.response.split("\n\n");
        
        lines = lines.filter(line => {
            const trimmed = line.trim();
            return trimmed.length > 0 && (trimmed.startsWith("[Alex]:") || trimmed.startsWith("[Jamie]:"));
        });
        
        let podcastSegmentsInOrder: ReadableStream<any>[] = [];

        for (let i = 0; i < lines.length; i++) {
            const line = lines[i];
            const text = line.trim().split(/\]:\s*/)[1]?.trim(); 

            if (!text) continue; 
            let audioStream: ReadableStream;

            if (line.startsWith("[Alex]:")) {
                // @ts-ignore
                audioStream = await env.AI.run("@cf/deepgram/aura-1", {
                    "text": text,
                    "speaker": "arcas" 
                });
                podcastSegmentsInOrder.push(audioStream);
            } else if (line.startsWith("[Jamie]:")) {
                // @ts-ignore
                audioStream = await env.AI.run("@cf/deepgram/aura-1", {
                    "text": text,
                    "speaker": "asteria"
                });
                podcastSegmentsInOrder.push(audioStream);
            }
            console.log(text + "\n");
        }
        return new Response(await combineReadableStreams(podcastSegmentsInOrder));
    },
} satisfies ExportedHandler<Env>;

async function combineReadableStreams(streams: ReadableStream[]): Promise<ReadableStream> {
  if (streams.length === 0) {
    throw new Error("No streams to combine");
  }
  
  if (streams.length === 1) {
    return streams[0];
  }
  
  // Create a new ReadableStream that will output all streams in sequence
  return new ReadableStream({
    async start(controller) {
      for (const stream of streams) {
        const reader = stream.getReader();
        try {
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            controller.enqueue(value);
          }
        } finally {
          reader.releaseLock();
        }
      }
      controller.close();
    }
  });
}
